[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "FqPyd6hhBjhk98jwkQkbRvzkSVPhiXVzoKgZ5mSU4TQ8"

[programs.devnet]
escrow = "FqPyd6hhBjhk98jwkQkbRvzkSVPhiXVzoKgZ5mSU4TQ8"

[programs.mainnet]
escrow = "FqPyd6hhBjhk98jwkQkbRvzkSVPhiXVzoKgZ5mSU4TQ8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
